### ISSUE TITLE
Question: How to populate List dynamically from _request

### ISSUE THREAD

**Issue by kemeris2000** [lowdefy/blocks-aggrid#16]
How to populate List block with array from _request.data?

According to manual https://docs.lowdefy.com/lists its possible with statically defined array.

```
contacts:
  - name: Name 1
    emails:
      - email1@example.com
      - email2@example.com
  - name: Name 2
    emails: []
```

```
id: contacts
type: ControlledList
properties:
  # ...
blocks:
  - id: contacts.$.name
    type: TextInput
    properties:
      # ...
  - id: contacts.$.emails
    type: ControlledList
    properties:
      # ...
    blocks:
      - id: contacts.$.emails.$
        type: TextInput
        properties:
          # ...
```

I would appreciate for help.
