### ISSUE TITLE
onRowSelected seems to trigger action multiple times for each selected row.

### ISSUE THREAD

**Issue by Gervwyk** [lowdefy/blocks-aggrid#8]
The following config on a table results in multiple row logs based on the number of selections or clicks.

```yaml
      events:
          onRowSelected:
            - id: set_selected
              type: SetState
              params:
                selected_row:
                  _log:
                    _event: row
```

The expected behavior is to only log once for a click, trigger the actions in the event list once.

Consider the implementation for both single and multiple row selection options, add examples for both to the readme.
