### ISSUE TITLE
Editing row of sorted & filtered table also changes another row

### ISSUE THREAD

**Issue by zaniar** [lowdefy/blocks-aggrid#9]
If you edit row X (counted from 0) in a sorted or filtered table, row with index X in the state alse changed.

Here is the config to reproduce the issue. There are test cases included in the bottom of the page.
```yaml
lowdefy: 3.23.1
name: Lowdefy starter

types:
  AgGridInputAlpine:
    url: https://blocks-cdn.lowdefy.com/v3.12.3/blocks-aggrid/meta/AgGridInputAlpine.json

pages:
  - id: ag-grid-edit-issue
    type: PageHeaderMenu
    events:
      onInit:
        - id: new
          type: SetState
          params:
            table:
              - a: zero
                b: 000
              - a: one
                b: 111
              - a: two
                b: 222
    blocks:
      - id: table
        type: AgGridInputAlpine
        properties:
          columnDefs:
            - field: "a"
              rowDrag: true
            - field: "b"
          defaultColDef:
            width: 170
            sortable: true
            filter: true
            editable: true
      - id: test-case
        type: Collapse
        properties:
          panels:
            - key: test-case-1
              title: Test Case 1 (Sorting)
            - key: test-case-2
              title: Test Case 2 (Filter)
        areas:
          test-case-1:
            blocks:
              - id: test-case-1-content
                type: Markdown
                properties:
                  content: |
                    1. Sort column **A** in ascending order
                    2. Edit `one` in row 1 column **A** to `nine`
                    3. Edit `111` in row 1 column **B** to `999`. 
                    4. Pay attention to row 3 column **A**.
                    5. Edit `two` in row 2 column **A** to `ten`
                    6. Pay attention to row 3 column **B**.
          test-case-2:
            blocks:
              - id: test-case-2-content
                type: Markdown
                properties:
                  content: |
                    1. Filter column **A** with *contains `two`*
                    2. Edit `two` in row 1 column **A** to `nine`
                    3. Remove the filter
                    4. Pay attention to row 1 column **A**.
```

Removing these line seems to fix the issue, but I don't know if this will affect other area.
https://github.com/lowdefy/blocks-aggrid/blob/4cbc69b7b2f67acc774d8a5e26bacdc75ce24be3/src/AgGridInput.js#L119-L120
